# Generated by Django 5.0.5 on 2024-05-08 04:43

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to='images/', validators=[myapp.models.FileTypeValidator(['.jpg', '.jpeg', '.png', '.gif', '.bmp', '.tiff', '.webp'])]),
        ),
    ]
