# Generated by Django 5.0.5 on 2024-05-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_image_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='image',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
